language: node_js
node_js:
    - '11'
dist: trusty
sudo: required
cache:
    yarn: true

branches:
    only:
        - master

before_install:
    # Repo for Yarn
    - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
    - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq yarn=1.16.0-1

before_script:
    - yarn global add @angular/cli
    - yarn global add firebase-tools

script:
    - yarn ci:test
    - ng build --prod

after_success:
    - firebase deploy --only hosting:skollstrength --token "$FIREBASE_TOKEN" --debug
